version: "3"
services:
  nginx:
    image: nginx:v3
    ports:
      - 80:80
    volumes:
      - /root/nginx/html:/usr/share/nginx/html
      - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis:latest
  vueblog:
    image: vueblog:latest
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - redis
